### ISSUE TITLE
google-services.json missing

### ISSUE THREAD

**Issue by thahgr** [natiginfo/QRScannerCameraX#13]
The project cannot build with the following error
"File google-services.json is missing"

Could you provide the relative file ?

**Comment by natiginfo** [comment]
Hi!
By following link provided in the "[Add Firebase to your Android project](https://firebase.google.com/docs/android/setup)" step of the [tutorial](https://www.natigbabayev.com/2019-07-13/building-qr-code-scanner-for-android-using-firebase-ml-kit-and-camerax), you can generate your own `google-services.json` file and add to the project.

**Comment by sudg6** [comment]
> Hi! By following link provided in the "[Add Firebase to your Android project](https://firebase.google.com/docs/android/setup)" step of the [tutorial](https://www.natigbabayev.com/2019-07-13/building-qr-code-scanner-for-android-using-firebase-ml-kit-and-camerax), you can generate your own `google-services.json` file and add to the project.

Why it doesn't come included in the repository?
